dist: trusty
language: node_js
node_js:
  - "10"
  - "11"
  - "12"
  - "13"
  - "14"
install:
  - npm install
script: npm run lint && npm run build && npm test
before_deploy: npm run build
deploy:
  provider: npm
  email: development@platforme.com
  skip_cleanup: true
  api_key:
    secure: VnL0LDB/AuN3J+gtM/TWDjXlRHm1hnahqi9+C/d9dVq7ixBwlNyF3AytqRXEk9HpNdNh7JN4Oqmo0afsg0pb91xOJxH3MTpBrFT8qabtK2G2WdcbOM2jPtIXlKG4UbC8tySfxthEsILm6iIQxb9Kz9kGRJGnSzhjprwgmB50dmvPBSRi70gTOk+GrrbT3cnuc/J/9sxMy+6LYF2Y+7Lrdms1trMmoljACWJtCsbYJzwilUipAd8zQ/FUVCFzu4mOpeA27n0ZjVfIJvAXZ1ampwnFv8Umbb0L0yHx7/TX/l9yyWB1zd2dwYgZTSCqLmB/yyQwhO1GMB+QaEwzbDoJO5HFnhnFOL70pJo0f7Sz+beom4YLyW3KNNucIA6H4bpmTiyNJf8dJzzqBCbc5y9bAu88f7O8g31q/Mm7WBvf4UBYr8cSL/QW1wGJVXoGOrYMmBHfxdEMk8RstdjGiHplmCH4LkvvBlZtFmoeZ/roLoeig0BA+cTNOAXrrVTQWbDMPeuDiYK9hb/cS2DA42CRUzDmUJK4duQBliP6SPEzvnXBCkAt0PcGZX5s2W/Gz//jWi5ztIWp/xmxGOE/nLnkyManI3FNMvJhU+hxWD/oNatKd2aR/T9H8E0u8Cvh1X3R6aFy+ZT2N380HS3s+RXmCfA92JwPvEgpE3RJXPtIDis=
  on:
    tags: true
    node_js: "10"
